onboarding = false

[keys]
prefix = "ctrl+h"
rename_tab = "prefix+comma"
rename_workspace = "prefix+shift+comma"

[[keys.command]]
key = "prefix+shift+g"
type = "pane"
command = "lazygit"
description = "lazygit"

[ui]
agent_panel_sort = "priority"

# send desktop notifications through Ghostty's escape sequences
[ui.toast]
delivery = "terminal"
delay_seconds = 1

[ui.toast.herdr]
position = "bottom-right"

[theme]
name = "terminal"

[theme.custom]
panel_bg = "transparent"
surface_dim = "#1f1f1f"
accent = "#326FD6"
