[mgr]
prepend_keymap = [
  { on = [ "g", "r" ], run = "shell --orphan 'open -R %h'", desc = "Reveal hovered file in Finder" },
  { on = [ "g", "h" ], run = "cd ~", desc = "Cd to home" },
  { on = [ "g", "0" ], run = 'shell -- for d in "$HOME"/Library/CloudStorage/GoogleDrive-*/"My Drive"; do [ -d "$d" ] && exec ya emit cd "$d"; done', desc = "Cd to Google Drive" },
  { on = [ "g", "t" ], run = "cd /tmp", desc = "Cd to /tmp" },
]
