# Warp Launch Configuration
#
#
# Use this to start a certain configuration of windows, tabs, and panes.
# Open the launch configuration palette to access and open any launch configuration.
#
# This file defines your launch configuration.
# More on how to do so here:
# https://docs.warp.dev/features/session-management/launch-configurations
#
# All launch configurations are stored under ~/.warp/launch_configurations.
# Edit them anytime!
#
# You can also add commands that run on-start for your launch configurations like so:
# ---
# name: Example with Command
# windows:
#  - tabs:
#      - layout:
#          cwd: /Users/warp-user/project
#          commands:
#            - exec: code .

---
name: Personal Launch Config
windows:
  - tabs:
      - layout:
          cwd: /Users/kg
      - title: Fragmented
        layout:
          split_direction: horizontal
          panes:
            - split_direction: vertical
              panes:
                - cwd: /Users/kg/src/per/fragmented/themes/henry
                - cwd: /Users/kg/src/per/fragmented
            - cwd: /Users/kg/src/per/fragmented
        color: cyan
      - title: kau.sh
        layout:
          split_direction: horizontal
          panes:
            - split_direction: vertical
              panes:
                - cwd: /Users/kg/src/per/kau.sh
                - cwd: /Users/kg/src/per/kau.sh
            - cwd: /Users/kg/src/per/kau.sh
        color: yellow
